const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('luma', {
  localStatus: () => ipcRenderer.invoke('local:status'),
  localConfigure: (values) => ipcRenderer.invoke('local:configure', values),
  localChoose: (kind) => ipcRenderer.invoke('local:choose', kind),
  localScan: () => ipcRenderer.invoke('local:scan'),
  setExpanded: (expanded) => ipcRenderer.invoke('window:set-expanded', expanded),
  setAlwaysOnTop: (enabled) => ipcRenderer.invoke('window:set-always-on-top', enabled),
  activate: () => ipcRenderer.send('window:activate'),
  hide: () => ipcRenderer.send('window:hide'),
  load: () => ipcRenderer.invoke('data:load'),
  save: (payload) => ipcRenderer.invoke('data:save', payload),
  exportData: (payload) => ipcRenderer.invoke('data:export', payload),
  setAutoStart: (enabled) => ipcRenderer.invoke('settings:auto-start', enabled),
  getAutoStart: () => ipcRenderer.invoke('settings:get-auto-start'),
  appVersion: () => ipcRenderer.invoke('app:version'),
  checkUpdates: () => ipcRenderer.invoke('app:check-updates'),
  resizeStart: (payload) => ipcRenderer.send('window:resize-start', payload),
  resizeMove: (payload) => ipcRenderer.send('window:resize-move', payload),
  resizeEnd: () => ipcRenderer.send('window:resize-end'),
  googleStatus: () => ipcRenderer.invoke('google:status'),
  googleConnect: () => ipcRenderer.invoke('google:connect'),
  googleDisconnect: () => ipcRenderer.invoke('google:disconnect'),
  googleSync: (payload) => ipcRenderer.invoke('google:sync', payload),
  googleDeleteTask: (task) => ipcRenderer.invoke('google:delete-task', task),
  icloudStatus: () => ipcRenderer.invoke('icloud:status'),
  icloudConnect: (payload) => ipcRenderer.invoke('icloud:connect', payload),
  icloudDisconnect: () => ipcRenderer.invoke('icloud:disconnect'),
  icloudSync: (payload) => ipcRenderer.invoke('icloud:sync', payload),
  lifelogLoad: () => ipcRenderer.invoke('lifelog:load'),
  lifelogSave: (payload) => ipcRenderer.invoke('lifelog:save', payload),
  lifelogMediaDataUrl: (relativePath) => ipcRenderer.invoke('lifelog:media-data-url', relativePath),
  lifelogSaveMedia: (payload) => ipcRenderer.invoke('lifelog:save-media', payload),
  lifelogDeleteMedia: (relativePath) => ipcRenderer.invoke('lifelog:delete-media', relativePath),
});
