function demoDateKey(offset = 0) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  const pad = (value) => String(value).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

function demoNextWeekday(targetDay, extraWeeks = 0) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  let delta = (targetDay - date.getDay() + 7) % 7;
  if (delta === 0) delta = 7;
  delta += extraWeeks * 7;
  return demoDateKey(delta);
}

function buildDemoState() {
  const now = Date.now();
  const projects = [
    { id: 'inbox', name: '未分类', color: '#8b8e92', order: 0, updatedAt: now },
    { id: 'work', name: '工作', color: '#5d8de0', order: 1, updatedAt: now },
    { id: 'product', name: '产品项目', color: '#4fb58f', order: 2, updatedAt: now },
    { id: 'study', name: '学习', color: '#a878ad', order: 3, updatedAt: now },
    { id: 'life', name: '生活', color: '#f58a3d', order: 4, updatedAt: now },
    { id: 'travel', name: '旅行计划', color: '#4aa6a1', order: 5, updatedAt: now },
  ];

  const nextFriday = demoNextWeekday(5);
  const fridayDate = new Date(`${nextFriday}T12:00:00`);
  const saturday = new Date(fridayDate);
  saturday.setDate(fridayDate.getDate() + 1);
  const sunday = new Date(fridayDate);
  sunday.setDate(fridayDate.getDate() + 2);
  const keyFor = (date) => {
    const pad = (value) => String(value).padStart(2, '0');
    return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  };

  return {
    version: 1,
    settings: {
      autoStart: false,
      googleConnected: false,
      panelOpacity: 96,
      alwaysOnTop: false,
      lightMode: true,
      collapsedProjectIds: [],
    },
    projects,
    projectsUpdatedAt: now,
    tasks: [
      {
        id: 'demo-todo-meeting-notes',
        title: '整理周会纪要',
        projectId: 'work',
        dueDate: demoDateKey(0),
        time: '10:00',
        itemType: 'todo',
        completed: false,
        createdAt: now - 7 * 86400000,
        updatedAt: now - 1800000,
        order: 10,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-todo-design-feedback',
        title: '提交设计反馈',
        projectId: 'product',
        dueDate: demoDateKey(1),
        time: '14:30',
        itemType: 'todo',
        completed: false,
        createdAt: now - 6 * 86400000,
        updatedAt: now - 1200000,
        order: 20,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-todo-product-docs',
        title: '阅读产品文档',
        projectId: 'study',
        dueDate: demoDateKey(2),
        time: '',
        itemType: 'todo',
        completed: false,
        createdAt: now - 5 * 86400000,
        updatedAt: now - 900000,
        order: 30,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-todo-health-check',
        title: '预约体检',
        projectId: 'life',
        dueDate: demoDateKey(4),
        time: '09:00',
        itemType: 'todo',
        completed: false,
        createdAt: now - 4 * 86400000,
        updatedAt: now - 600000,
        order: 40,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-todo-presentation',
        title: '准备项目演示',
        projectId: 'product',
        dueDate: demoDateKey(6),
        time: '',
        itemType: 'todo',
        completed: false,
        createdAt: now - 3 * 86400000,
        updatedAt: now - 480000,
        order: 50,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-todo-gift',
        title: '购买生日礼物',
        projectId: 'life',
        dueDate: demoDateKey(3),
        time: '',
        itemType: 'todo',
        completed: false,
        createdAt: now - 2 * 86400000,
        updatedAt: now - 420000,
        order: 60,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-todo-trip-list',
        title: '整理旅行清单',
        projectId: 'travel',
        dueDate: keyFor(saturday),
        time: '',
        itemType: 'todo',
        completed: false,
        createdAt: now - 86400000,
        updatedAt: now - 360000,
        order: 70,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-completed-room',
        title: '确认会议室预订',
        projectId: 'work',
        dueDate: demoDateKey(-1),
        completedDate: demoDateKey(-1),
        time: '',
        itemType: 'todo',
        completed: true,
        createdAt: now - 8 * 86400000,
        updatedAt: now - 20 * 3600000,
        order: 80,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-completed-release-notes',
        title: '更新版本说明',
        projectId: 'product',
        dueDate: demoDateKey(0),
        completedDate: demoDateKey(0),
        time: '',
        itemType: 'todo',
        completed: true,
        createdAt: now - 5 * 86400000,
        updatedAt: now - 2 * 3600000,
        order: 90,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-event-standup',
        title: '团队晨会',
        projectId: 'inbox',
        dueDate: demoDateKey(0),
        endDate: demoDateKey(0),
        time: '09:30',
        endTime: '10:00',
        eventColor: '#039be5',
        itemType: 'event',
        completed: false,
        createdAt: now - 9 * 86400000,
        updatedAt: now - 240000,
        order: 100,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-event-review',
        title: '产品评审',
        projectId: 'inbox',
        dueDate: demoDateKey(1),
        endDate: demoDateKey(1),
        time: '14:00',
        endTime: '15:00',
        eventColor: '#e67c73',
        itemType: 'event',
        completed: false,
        createdAt: now - 8 * 86400000,
        updatedAt: now - 180000,
        order: 110,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-event-health',
        title: '年度体检',
        projectId: 'inbox',
        dueDate: demoDateKey(4),
        endDate: demoDateKey(4),
        time: '',
        endTime: '',
        eventColor: '#33b679',
        itemType: 'event',
        completed: false,
        createdAt: now - 7 * 86400000,
        updatedAt: now - 120000,
        order: 120,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-event-sharing',
        title: '线上分享会',
        projectId: 'inbox',
        dueDate: demoDateKey(6),
        endDate: demoDateKey(6),
        time: '19:30',
        endTime: '20:30',
        eventColor: '#8e24aa',
        itemType: 'event',
        completed: false,
        createdAt: now - 6 * 86400000,
        updatedAt: now - 90000,
        order: 130,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-event-weekend-trip',
        title: '周末短途旅行',
        projectId: 'inbox',
        dueDate: nextFriday,
        endDate: keyFor(sunday),
        time: '',
        endTime: '',
        eventColor: '#f4511e',
        itemType: 'event',
        completed: false,
        createdAt: now - 5 * 86400000,
        updatedAt: now - 60000,
        order: 140,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-todo-user-feedback',
        title: '整理用户反馈',
        projectId: 'product',
        dueDate: demoDateKey(10),
        time: '',
        itemType: 'todo',
        completed: false,
        createdAt: now - 4 * 86400000,
        updatedAt: now - 55000,
        order: 150,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-event-milestone',
        title: '项目里程碑评审',
        projectId: 'inbox',
        dueDate: demoDateKey(12),
        endDate: demoDateKey(12),
        time: '15:00',
        endTime: '16:00',
        eventColor: '#3f51b5',
        itemType: 'event',
        completed: false,
        createdAt: now - 4 * 86400000,
        updatedAt: now - 50000,
        order: 160,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-event-client-call',
        title: '客户沟通',
        projectId: 'inbox',
        dueDate: demoDateKey(14),
        endDate: demoDateKey(14),
        time: '11:00',
        endTime: '11:45',
        eventColor: '#f6bf26',
        itemType: 'event',
        completed: false,
        createdAt: now - 4 * 86400000,
        updatedAt: now - 48000,
        order: 170,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-todo-course-practice',
        title: '完成课程练习',
        projectId: 'study',
        dueDate: demoDateKey(15),
        time: '20:00',
        itemType: 'todo',
        completed: false,
        createdAt: now - 3 * 86400000,
        updatedAt: now - 45000,
        order: 180,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-event-design-check',
        title: '设计走查',
        projectId: 'inbox',
        dueDate: demoDateKey(17),
        endDate: demoDateKey(17),
        time: '10:30',
        endTime: '11:30',
        eventColor: '#00a6a6',
        itemType: 'event',
        completed: false,
        createdAt: now - 3 * 86400000,
        updatedAt: now - 42000,
        order: 190,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-completed-archive',
        title: '完成资料归档',
        projectId: 'work',
        dueDate: demoDateKey(18),
        completedDate: demoDateKey(18),
        time: '',
        itemType: 'todo',
        completed: true,
        createdAt: now - 3 * 86400000,
        updatedAt: now - 40000,
        order: 200,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-todo-expense',
        title: '整理报销资料',
        projectId: 'work',
        dueDate: demoDateKey(19),
        time: '',
        itemType: 'todo',
        completed: false,
        createdAt: now - 2 * 86400000,
        updatedAt: now - 38000,
        order: 210,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-event-dinner',
        title: '朋友聚餐',
        projectId: 'inbox',
        dueDate: demoDateKey(21),
        endDate: demoDateKey(21),
        time: '18:30',
        endTime: '20:00',
        eventColor: '#ff2d55',
        itemType: 'event',
        completed: false,
        createdAt: now - 2 * 86400000,
        updatedAt: now - 34000,
        order: 220,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-todo-travel-supplies',
        title: '采购旅行用品',
        projectId: 'travel',
        dueDate: demoDateKey(23),
        time: '',
        itemType: 'todo',
        completed: false,
        createdAt: now - 2 * 86400000,
        updatedAt: now - 30000,
        order: 230,
        syncTarget: 'tasks',
      },
      {
        id: 'demo-event-monthly-review',
        title: '月度复盘',
        projectId: 'inbox',
        dueDate: demoDateKey(24),
        endDate: demoDateKey(24),
        time: '16:00',
        endTime: '17:00',
        eventColor: '#8e24aa',
        itemType: 'event',
        completed: false,
        createdAt: now - 86400000,
        updatedAt: now - 26000,
        order: 240,
        syncTarget: 'calendar',
      },
      {
        id: 'demo-todo-next-month',
        title: '制定下月计划',
        projectId: 'work',
        dueDate: demoDateKey(26),
        time: '10:30',
        itemType: 'todo',
        completed: false,
        createdAt: now - 86400000,
        updatedAt: now - 22000,
        order: 250,
        syncTarget: 'tasks',
      },
    ],
  };
}

module.exports = { buildDemoState };
